# Generated by Django 4.1.13 on 2026-01-31 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título completo del libro (máximo 200 caracteres)",
                        max_length=200,
                        verbose_name="Título del Libro",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        help_text="Nombre del autor o autores",
                        max_length=100,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="Código ISBN único (formato: 978-3-16-148410-0)",
                        max_length=17,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateField(
                        help_text="Fecha original de publicación del libro",
                        verbose_name="Fecha de Publicación",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del libro (formato: 000000.00)",
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de ejemplares en inventario",
                        verbose_name="Stock Disponible",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del contenido del libro",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, el libro está disponible en el sistema",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_prestamo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Préstamo"
                    ),
                ),
                (
                    "fecha_devolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Devolución"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("DEVUELTO", "Devuelto"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "dias_prestamo",
                    models.IntegerField(default=14, verbose_name="Días de Préstamo"),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                        verbose_name="Libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "db_table": "biblioteca_prestamo",
                "ordering": ["-fecha_prestamo"],
            },
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Monto"
                    ),
                ),
                ("pagada", models.BooleanField(default=False, verbose_name="Pagada")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.prestamo",
                        verbose_name="Préstamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multa",
                "verbose_name_plural": "Multas",
                "db_table": "biblioteca_multa",
            },
        ),
        migrations.AddIndex(
            model_name="libro",
            index=models.Index(fields=["isbn"], name="biblioteca__isbn_441a3a_idx"),
        ),
        migrations.AddIndex(
            model_name="libro",
            index=models.Index(fields=["autor"], name="biblioteca__autor_2143be_idx"),
        ),
        migrations.AddIndex(
            model_name="libro",
            index=models.Index(fields=["titulo"], name="biblioteca__titulo_c16bf1_idx"),
        ),
    ]
